// App Strings
export const APP_STRINGS = {
  // App Info
  APP_NAME: 'Boundary',
  APP_TAGLINE: 'Connecting Families, Ensuring Safety',
  APP_DESCRIPTION: 'The ultimate Circle safety and communication platform',
  
  // Navigation
  NAVIGATION: {
    HOME: 'Home',
    CALENDAR: 'Calendar',
    APPLICATIONS: 'Apps',
    PROFILE: 'Profile',
    SETTINGS: 'Settings',
    Circle: 'Circle',
    SAFETY: 'Safety',
    CHAT: 'Chat',
  },

  // Common Actions
  ACTIONS: {
    SAVE: 'Save',
    CANCEL: 'Cancel',
    DELETE: 'Delete',
    EDIT: 'Edit',
    ADD: 'Add',
    REMOVE: 'Remove',
    UPDATE: 'Update',
    CREATE: 'Create',
    JOIN: 'Join',
    LEAVE: 'Leave',
    INVITE: 'Invite',
    ACCEPT: 'Accept',
    DECLINE: 'Decline',
    SEND: 'Send',
    SHARE: 'Share',
    DOWNLOAD: 'Download',
    UPLOAD: 'Upload',
    SEARCH: 'Search',
    FILTER: 'Filter',
    SORT: 'Sort',
    REFRESH: 'Refresh',
    RETRY: 'Retry',
    CONTINUE: 'Continue',
    BACK: 'Back',
    NEXT: 'Next',
    PREVIOUS: 'Previous',
    CLOSE: 'Close',
    OPEN: 'Open',
    START: 'Start',
    STOP: 'Stop',
    PAUSE: 'Pause',
    RESUME: 'Resume',
    CONFIRM: 'Confirm',
    YES: 'Yes',
    NO: 'No',
    OK: 'OK',
    DONE: 'Done',
    SKIP: 'Skip',
    FINISH: 'Finish',
  },

  // Authentication
  AUTH: {
    LOGIN: 'Login',
    REGISTER: 'Register',
    LOGOUT: 'Logout',
    FORGOT_PASSWORD: 'Forgot Password?',
    RESET_PASSWORD: 'Reset Password',
    CHANGE_PASSWORD: 'Change Password',
    VERIFY_EMAIL: 'Verify Email',
    EMAIL: 'Email',
    PASSWORD: 'Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    CURRENT_PASSWORD: 'Current Password',
    NEW_PASSWORD: 'New Password',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    PHONE_NUMBER: 'Phone Number',
    DATE_OF_BIRTH: 'Date of Birth',
    GENDER: 'Gender',
    REMEMBER_ME: 'Remember Me',
    SIGN_IN_WITH: 'Sign in with',
    SIGN_UP_WITH: 'Sign up with',
    ALREADY_HAVE_ACCOUNT: 'Already have an account?',
    DONT_HAVE_ACCOUNT: "Don't have an account?",
    FORGOT_PASSWORD_QUESTION: 'Forgot your password?',
    RESET_PASSWORD_INSTRUCTIONS: 'Enter your email address and we will send you a link to reset your password.',
    VERIFY_EMAIL_INSTRUCTIONS: 'Please check your email and click the verification link to activate your account.',
    PASSWORD_REQUIREMENTS: 'Password must be at least 8 characters long and contain uppercase, lowercase, number, and special character.',
    TERMS_AND_CONDITIONS: 'I agree to the Terms and Conditions',
    PRIVACY_POLICY: 'Privacy Policy',
    ACCEPT_TERMS: 'By creating an account, you agree to our',
  },

  // Circle
  Circle: {
    Circle: 'Circle',
    FAMILIES: 'Families',
    CIRCLE_NAME: 'Circle Name',
    CIRCLE_DESCRIPTION: 'Circle Description',
    CIRCLE_MEMBERS: 'Circle Members',
    CIRCLE_SETTINGS: 'Circle Settings',
    CIRCLE_INVITATIONS: 'Circle Invitations',
    CREATE_CIRCLE: 'Create Circle',
    JOIN_CIRCLE: 'Join Circle',
    LEAVE_CIRCLE: 'Leave Circle',
    INVITE_MEMBER: 'Invite Member',
    REMOVE_MEMBER: 'Remove Member',
    UPDATE_ROLE: 'Update Role',
    CIRCLE_ROLE: 'Circle Role',
    ADMIN: 'Admin',
    MODERATOR: 'Moderator',
    MEMBER: 'Member',
    GUEST: 'Guest',
    INVITATION_SENT: 'Invitation sent successfully',
    INVITATION_ACCEPTED: 'Invitation accepted',
    INVITATION_DECLINED: 'Invitation declined',
    INVITATION_EXPIRED: 'Invitation expired',
    ALREADY_MEMBER: 'You are already a member of this Circle',
    NOT_CIRCLE_MEMBER: 'You are not a member of this Circle',
    CIRCLE_CREATED: 'Circle created successfully',
    CIRCLE_JOINED: 'Successfully joined Circle',
    CIRCLE_LEFT: 'Successfully left Circle',
    MEMBER_ADDED: 'Member added successfully',
    MEMBER_REMOVED: 'Member removed successfully',
    ROLE_UPDATED: 'Role updated successfully',
  },

  // Safety
  SAFETY: {
    SAFETY: 'Safety',
    SAFETY_CHECK: 'Safety Check',
    EMERGENCY: 'Emergency',
    EMERGENCY_ALERT: 'Emergency Alert',
    EMERGENCY_CONTACTS: 'Emergency Contacts',
    LOCATION: 'Location',
    LOCATION_HISTORY: 'Location History',
    LOCATION_SHARING: 'Location Sharing',
    GEOFENCE: 'Geofence',
    GEOFENCE_ALERTS: 'Geofence Alerts',
    CRISIS_MODE: 'Crisis Mode',
    SAFE_ZONE: 'Safe Zone',
    DANGER_ZONE: 'Danger Zone',
    CHECK_IN: 'Check In',
    CHECK_OUT: 'Check Out',
    I_AM_SAFE: 'I am safe',
    I_NEED_HELP: 'I need help',
    SEND_ALERT: 'Send Alert',
    CANCEL_ALERT: 'Cancel Alert',
    ALERT_SENT: 'Alert sent successfully',
    ALERT_CANCELLED: 'Alert cancelled',
    SAFETY_CHECK_SENT: 'Safety check sent',
    SAFETY_CHECK_RESPONDED: 'Safety check responded',
    LOCATION_UPDATED: 'Location updated',
    GEOFENCE_CREATED: 'Geofence created',
    GEOFENCE_UPDATED: 'Geofence updated',
    GEOFENCE_DELETED: 'Geofence deleted',
    ENTERED_GEOFENCE: 'Entered geofence',
    EXITED_GEOFENCE: 'Exited geofence',
  },

  // Chat
  CHAT: {
    CHAT: 'Chat',
    MESSAGES: 'Messages',
    NEW_MESSAGE: 'New Message',
    SEND_MESSAGE: 'Send Message',
    TYPE_MESSAGE: 'Type a message...',
    ATTACH_FILE: 'Attach File',
    TAKE_PHOTO: 'Take Photo',
    RECORD_VOICE: 'Record Voice',
    SHARE_LOCATION: 'Share Location',
    MESSAGE_SENT: 'Message sent',
    MESSAGE_DELIVERED: 'Message delivered',
    MESSAGE_READ: 'Message read',
    NO_MESSAGES: 'No messages yet',
    START_CONVERSATION: 'Start a conversation',
    SEARCH_MESSAGES: 'Search messages',
    CLEAR_CHAT: 'Clear Chat',
    DELETE_CHAT: 'Delete Chat',
    BLOCK_USER: 'Block User',
    UNBLOCK_USER: 'Unblock User',
    REPORT_USER: 'Report User',
  },

  // Profile
  PROFILE: {
    PROFILE: 'Profile',
    EDIT_PROFILE: 'Edit Profile',
    VIEW_PROFILE: 'View Profile',
    PERSONAL_INFO: 'Personal Information',
    CONTACT_INFO: 'Contact Information',
    PREFERENCES: 'Preferences',
    PRIVACY: 'Privacy',
    SECURITY: 'Security',
    NOTIFICATIONS: 'Notifications',
    ACCOUNT: 'Account',
    DELETE_ACCOUNT: 'Delete Account',
    DEACTIVATE_ACCOUNT: 'Deactivate Account',
    LOGOUT: 'Logout',
    AVATAR: 'Avatar',
    COVER_PHOTO: 'Cover Photo',
    BIO: 'Bio',
    ABOUT: 'About',
    WEBSITE: 'Website',
    SOCIAL_MEDIA: 'Social Media',
    SKILLS: 'Skills',
    INTERESTS: 'Interests',
    HOBBIES: 'Hobbies',
    OCCUPATION: 'Occupation',
    COMPANY: 'Company',
    EDUCATION: 'Education',
    LOCATION: 'Location',
    BIRTHDAY: 'Birthday',
    AGE: 'Age',
    GENDER: 'Gender',
    RELATIONSHIP_STATUS: 'Relationship Status',
    SINGLE: 'Single',
    IN_RELATIONSHIP: 'In a Relationship',
    MARRIED: 'Married',
    DIVORCED: 'Divorced',
    WIDOWED: 'Widowed',
  },

  // Settings
  SETTINGS: {
    SETTINGS: 'Settings',
    GENERAL: 'General',
    APPEARANCE: 'Appearance',
    LANGUAGE: 'Language',
    THEME: 'Theme',
    LIGHT: 'Light',
    DARK: 'Dark',
    AUTO: 'Auto',
    FONT_SIZE: 'Font Size',
    SMALL: 'Small',
    MEDIUM: 'Medium',
    LARGE: 'Large',
    EXTRA_LARGE: 'Extra Large',
    SOUND: 'Sound',
    VIBRATION: 'Vibration',
    HAPTIC_FEEDBACK: 'Haptic Feedback',
    AUTO_PLAY: 'Auto Play',
    QUALITY: 'Quality',
    LOW: 'Low',
    HIGH: 'High',
    STORAGE: 'Storage',
    CACHE: 'Cache',
    CLEAR_CACHE: 'Clear Cache',
    DATA_USAGE: 'Data Usage',
    BANDWIDTH: 'Bandwidth',
    SYNC: 'Sync',
    BACKUP: 'Backup',
    RESTORE: 'Restore',
    EXPORT: 'Export',
    IMPORT: 'Import',
    RESET: 'Reset',
    FACTORY_RESET: 'Factory Reset',
    ABOUT: 'About',
    VERSION: 'Version',
    BUILD: 'Build',
    LICENSES: 'Licenses',
    TERMS_OF_SERVICE: 'Terms of Service',
    PRIVACY_POLICY: 'Privacy Policy',
    COOKIE_POLICY: 'Cookie Policy',
    HELP: 'Help',
    SUPPORT: 'Support',
    FEEDBACK: 'Feedback',
    RATE_APP: 'Rate App',
    SHARE_APP: 'Share App',
  },

  // Notifications
  NOTIFICATIONS: {
    NOTIFICATIONS: 'Notifications',
    PUSH_NOTIFICATIONS: 'Push Notifications',
    EMAIL_NOTIFICATIONS: 'Email Notifications',
    SMS_NOTIFICATIONS: 'SMS Notifications',
    IN_APP_NOTIFICATIONS: 'In-App Notifications',
    CIRCLE_NOTIFICATIONS: 'Circle Notifications',
    MESSAGE_NOTIFICATIONS: 'Message Notifications',
    SAFETY_NOTIFICATIONS: 'Safety Notifications',
    EMERGENCY_NOTIFICATIONS: 'Emergency Notifications',
    EVENT_NOTIFICATIONS: 'Event Notifications',
    REMINDER_NOTIFICATIONS: 'Reminder Notifications',
    MARKETING_NOTIFICATIONS: 'Marketing Notifications',
    SOUND: 'Sound',
    VIBRATION: 'Vibration',
    BADGE: 'Badge',
    PREVIEW: 'Preview',
    QUIET_HOURS: 'Quiet Hours',
    DO_NOT_DISTURB: 'Do Not Disturb',
    ALLOW_NOTIFICATIONS: 'Allow Notifications',
    NOTIFICATION_PERMISSION: 'Notification Permission',
    GRANT_PERMISSION: 'Grant Permission',
    DENY_PERMISSION: 'Deny Permission',
  },

  // Privacy
  PRIVACY: {
    PRIVACY: 'Privacy',
    PRIVACY_SETTINGS: 'Privacy Settings',
    PROFILE_VISIBILITY: 'Profile Visibility',
    PUBLIC: 'Public',
    PRIVATE: 'Private',
    FRIENDS_ONLY: 'Friends Only',
    CIRCLE_ONLY: 'Circle Only',
    LOCATION_SHARING: 'Location Sharing',
    ACTIVITY_SHARING: 'Activity Sharing',
    DATA_SHARING: 'Data Sharing',
    ANALYTICS: 'Analytics',
    MARKETING: 'Marketing',
    THIRD_PARTY: 'Third Party',
    SEARCH_VISIBILITY: 'Search Visibility',
    ALLOW_SEARCH: 'Allow Search',
    SHOW_IN_RESULTS: 'Show in Results',
    BLOCKED_USERS: 'Blocked Users',
    BLOCK_USER: 'Block User',
    UNBLOCK_USER: 'Unblock User',
    REPORT_USER: 'Report User',
    DATA_DELETION: 'Data Deletion',
    DELETE_DATA: 'Delete Data',
    EXPORT_DATA: 'Export Data',
    COOKIES: 'Cookies',
    ACCEPT_COOKIES: 'Accept Cookies',
    REJECT_COOKIES: 'Reject Cookies',
  },

  // Security
  SECURITY: {
    SECURITY: 'Security',
    SECURITY_SETTINGS: 'Security Settings',
    TWO_FACTOR_AUTH: 'Two-Factor Authentication',
    BIOMETRIC_AUTH: 'Biometric Authentication',
    FINGERPRINT: 'Fingerprint',
    FACE_ID: 'Face ID',
    TOUCH_ID: 'Touch ID',
    PIN_CODE: 'PIN Code',
    PASSWORD: 'Password',
    SECURITY_QUESTIONS: 'Security Questions',
    LOGIN_ALERTS: 'Login Alerts',
    DEVICE_MANAGEMENT: 'Device Management',
    ACTIVE_SESSIONS: 'Active Sessions',
    LOGOUT_ALL_DEVICES: 'Logout All Devices',
    ACCOUNT_LOCKOUT: 'Account Lockout',
    SUSPICIOUS_ACTIVITY: 'Suspicious Activity',
    ENCRYPTION: 'Encryption',
    END_TO_END_ENCRYPTION: 'End-to-End Encryption',
    DATA_ENCRYPTION: 'Data Encryption',
    BACKUP_ENCRYPTION: 'Backup Encryption',
  },

  // Applications
  APPLICATIONS: {
    APPLICATIONS: 'Applications',
    APPS: 'Apps',
    GALLERY: 'Gallery',
    NOTES: 'Notes',
    CALENDAR: 'Calendar',
    GOALS: 'Goals',
    GAMES: 'Games',
    MUSIC: 'Music',
    VIDEOS: 'Videos',
    BILLING: 'Billing',
    SHOPPING: 'Shopping',
    HEALTH: 'Health',
    EDUCATION: 'Education',
    STORAGE: 'Storage',
    FILES: 'Files',
    DOCUMENTS: 'Documents',
    PHOTOS: 'Photos',
    VIDEOS: 'Videos',
    AUDIO: 'Audio',
    BOOKMARKS: 'Bookmarks',
    FAVORITES: 'Favorites',
    RECENT: 'Recent',
    DOWNLOADS: 'Downloads',
    UPLOADS: 'Uploads',
    SHARED: 'Shared',
    TRASH: 'Trash',
    RECYCLE_BIN: 'Recycle Bin',
  },

  // Status Messages
  STATUS: {
    LOADING: 'Loading...',
    SAVING: 'Saving...',
    UPLOADING: 'Uploading...',
    DOWNLOADING: 'Downloading...',
    PROCESSING: 'Processing...',
    SEARCHING: 'Searching...',
    SYNCING: 'Syncing...',
    CONNECTING: 'Connecting...',
    DISCONNECTING: 'Disconnecting...',
    ONLINE: 'Online',
    OFFLINE: 'Offline',
    AWAY: 'Away',
    BUSY: 'Busy',
    AVAILABLE: 'Available',
    UNAVAILABLE: 'Unavailable',
    TYPING: 'Typing...',
    RECORDING: 'Recording...',
    PLAYING: 'Playing...',
    PAUSED: 'Paused',
    STOPPED: 'Stopped',
    COMPLETED: 'Completed',
    FAILED: 'Failed',
    CANCELLED: 'Cancelled',
    PENDING: 'Pending',
    APPROVED: 'Approved',
    REJECTED: 'Rejected',
    EXPIRED: 'Expired',
    ACTIVE: 'Active',
    INACTIVE: 'Inactive',
    ENABLED: 'Enabled',
    DISABLED: 'Disabled',
  },

  // Error Messages
  ERRORS: {
    NETWORK_ERROR: 'Network connection failed. Please check your internet connection.',
    TIMEOUT_ERROR: 'Request timed out. Please try again.',
    SERVER_ERROR: 'Server error occurred. Please try again later.',
    UNKNOWN_ERROR: 'An unknown error occurred. Please try again.',
    VALIDATION_ERROR: 'Please check your input and try again.',
    PERMISSION_DENIED: 'Permission denied. Please check your settings.',
    FILE_NOT_FOUND: 'File not found.',
    FILE_TOO_LARGE: 'File size exceeds the maximum limit.',
    INVALID_FILE_TYPE: 'File type not supported.',
    UPLOAD_FAILED: 'File upload failed. Please try again.',
    DOWNLOAD_FAILED: 'File download failed. Please try again.',
    SAVE_FAILED: 'Failed to save. Please try again.',
    DELETE_FAILED: 'Failed to delete. Please try again.',
    UPDATE_FAILED: 'Failed to update. Please try again.',
    CREATE_FAILED: 'Failed to create. Please try again.',
    LOGIN_FAILED: 'Login failed. Please check your credentials.',
    REGISTER_FAILED: 'Registration failed. Please try again.',
    PASSWORD_MISMATCH: 'Passwords do not match.',
    INVALID_EMAIL: 'Please enter a valid email address.',
    INVALID_PHONE: 'Please enter a valid phone number.',
    REQUIRED_FIELD: 'This field is required.',
    MIN_LENGTH: 'Minimum length is {min} characters.',
    MAX_LENGTH: 'Maximum length is {max} characters.',
  },

  // Success Messages
  SUCCESS: {
    SAVED: 'Saved successfully.',
    UPDATED: 'Updated successfully.',
    CREATED: 'Created successfully.',
    DELETED: 'Deleted successfully.',
    UPLOADED: 'Uploaded successfully.',
    DOWNLOADED: 'Downloaded successfully.',
    SENT: 'Sent successfully.',
    SHARED: 'Shared successfully.',
    LOGGED_IN: 'Logged in successfully.',
    REGISTERED: 'Registered successfully.',
    LOGGED_OUT: 'Logged out successfully.',
    PASSWORD_CHANGED: 'Password changed successfully.',
    PROFILE_UPDATED: 'Profile updated successfully.',
    SETTINGS_SAVED: 'Settings saved successfully.',
    NOTIFICATION_SENT: 'Notification sent successfully.',
    INVITATION_SENT: 'Invitation sent successfully.',
    REQUEST_SENT: 'Request sent successfully.',
    ACTION_COMPLETED: 'Action completed successfully.',
  },

  // Confirmation Messages
  CONFIRMATIONS: {
    DELETE_CONFIRMATION: 'Are you sure you want to delete this?',
    LOGOUT_CONFIRMATION: 'Are you sure you want to logout?',
    LEAVE_CIRCLE_CONFIRMATION: 'Are you sure you want to leave this Circle?',
    REMOVE_MEMBER_CONFIRMATION: 'Are you sure you want to remove this member?',
    DELETE_ACCOUNT_CONFIRMATION: 'Are you sure you want to delete your account? This action cannot be undone.',
    CLEAR_CACHE_CONFIRMATION: 'Are you sure you want to clear the cache?',
    RESET_SETTINGS_CONFIRMATION: 'Are you sure you want to reset all settings?',
    CANCEL_ACTION_CONFIRMATION: 'Are you sure you want to cancel? Any unsaved changes will be lost.',
    DISCARD_CHANGES_CONFIRMATION: 'Are you sure you want to discard your changes?',
    OVERWRITE_FILE_CONFIRMATION: 'A file with this name already exists. Do you want to overwrite it?',
  },

  // Empty States
  EMPTY_STATES: {
    NO_DATA: 'No data available',
    NO_MESSAGES: 'No messages yet',
    NO_FAMILIES: 'No families yet',
    NO_MEMBERS: 'No members yet',
    NO_INVITATIONS: 'No invitations yet',
    NO_EVENTS: 'No events yet',
    NO_FILES: 'No files yet',
    NO_PHOTOS: 'No photos yet',
    NO_VIDEOS: 'No videos yet',
    NO_NOTES: 'No notes yet',
    NO_GOALS: 'No goals yet',
    NO_GAMES: 'No games yet',
    NO_MUSIC: 'No music yet',
    NO_BILLING: 'No billing yet',
    NO_SHOPPING: 'No shopping yet',
    NO_HEALTH: 'No health data yet',
    NO_EDUCATION: 'No education data yet',
    NO_RESULTS: 'No results found',
    NO_CONNECTIONS: 'No connections yet',
    NO_ACTIVITY: 'No activity yet',
    NO_NOTIFICATIONS: 'No notifications yet',
    NO_SEARCH_RESULTS: 'No search results found',
    NO_FILTER_RESULTS: 'No items match your filter',
    NO_FAVORITES: 'No favorites yet',
    NO_RECENT: 'No recent items',
    NO_DOWNLOADS: 'No downloads yet',
    NO_UPLOADS: 'No uploads yet',
    NO_SHARED: 'No shared items yet',
  },
}; 

